CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(256) NOT NULL,
  CHECK(name > '')
);
CREATE SEQUENCE NR_USER_ID_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

CREATE TABLE transaction (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  source_currency VARCHAR(3) NOT NULL,
  target_currency VARCHAR(3) NOT NULL,
  source_value DECIMAL NOT NULL,
  conversion_rate DECIMAL NOT NULL,
  date_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  foreign key (user_id) references user(id)
);
CREATE SEQUENCE NR_TRANSACTION_ID_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

